prowjob_namespace: prow
pod_namespace: prow-test-pods
log_level: debug

branch-protection:
  enforce_admins: true # rules apply to admins too!
  orgs:
    tidb-community-bots:
      repos:
        test-dev:
          branches:
            master:
              protect: true
              required_status_checks:
                contexts:
                  - "Semantic Pull Request"
                strict: true

in_repo_config:
  enabled:
    tidb-community-bots/test-dev: true

deck:
  spyglass:
    lenses:
      - lens:
          name: metadata
        required_files:
          - started.json|finished.json
      - lens:
          config:
          name: buildlog
        required_files:
          - build-log.txt
      - lens:
          name: junit
        required_files:
          - .*/junit.*\.xml
      - lens:
          name: podinfo
        required_files:
          - podinfo.json

plank:
  job_url_prefix_config:
    "*": https://prow-dev.tidb.io/view/
  report_templates:
    '*': >-
      [Full PR test history](https://prow-dev.tidb.io/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}).
      [Your PR dashboard](https://prow-dev.tidb.io/pr?query=is%3Apr%20state%3Aopen%20author%3A{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}).
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: gs://prow-dev-tidb-logs
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20201217-2de500de27
        entrypoint: gcr.io/k8s-prow/entrypoint:v20201217-2de500de27
        initupload: gcr.io/k8s-prow/initupload:v20201217-2de500de27
        sidecar: gcr.io/k8s-prow/sidecar:v20201217-2de500de27

tide:
  sync_period: 1m

  merge_method:
    tidb-community-bots/test-dev: squash

  target_url: https://prow-dev.tidb.io/tide

  queries:
    - repos:
        - tidb-community-bots/test-dev
      labels:
        - status/can-merge
      missingLabels:
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-rebase

  context_options:
    orgs:
      tidb-community-bots:
        repos:
          test-dev:
            from-branch-protection: true