ti-community-lgtm:
  - repos:
      - tidb-community-bots/test-dev
    review_acts_as_lgtm: true
    pull_owners_endpoint: https://prow-dev.tidb.io/ti-community-owners

ti-community-merge:
  - repos:
      - tidb-community-bots/test-dev
    store_tree_hash: true
    pull_owners_endpoint: https://prow-dev.tidb.io/ti-community-owners

ti-community-owners:
  - repos:
      - tidb-community-bots/test-dev
    default_require_lgtm: 1
    sig_endpoint: https://bots.tidb.io/ti-community-bot

ti-community-label:
  - repos:
      - tidb-community-bots/test-dev
    prefixes:
      - type
      - status
    exclude_labels:
      - status/can-merge

ti-community-autoresponder:
  - repos:
      - tidb-community-bots/test-dev
    auto_responds:
      - regex: "(?mi)^/ping\\s*$"
        message: "pong"

ti-community-blunderbuss:
  - repos:
      - tidb-community-bots/test-dev
    pull_owners_endpoint: https://prow-dev.tidb.io/ti-community-owners
    max_request_count: 1
    exclude_reviewers:
      # Bots
      - ti-community-prow-bot
      - rustin-bot
      # Inactive reviewers
      - sykp241095
      - AndreMouche