apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: prow
  name: prow
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prow-static-ip
spec:
  rules:
    - host: prow.tidb.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: deck
              servicePort: 80
          - path: /hook
            backend:
              serviceName: hook
              servicePort: 8888
  tls:
    - hosts:
        - "*.tidb.io"
      secretName: prow-tidb-io