kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio
  namespace: prow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: prow
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio
      initContainers:
        - name: bucket-creator
          image: alpine
          command:
            - mkdir
            - -p
            - /data/prow-logs
            - /data/tide
            - /data/status-reconciler
          volumeMounts:
            - name: data
              mountPath: "/data"
      containers:
        - name: minio
          volumeMounts:
            - name: data
              mountPath: "/data"
          image: minio/minio:latest
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: "<<CHANGE_ME_MINIO_ACCESS_KEY>>"
            - name: MINIO_SECRET_KEY
              value: "<<CHANGE_ME_MINIO_SECRET_KEY>>"
            - name: MINIO_REGION_NAME
              value: minio
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: prow
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
