---
apiVersion: v1
kind: Secret
metadata:
  namespace: prow
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "minio",
      "access_key": "<<CHANGE_ME_MINIO_ACCESS_KEY>>",
      "endpoint": "minio.prow.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": "<<CHANGE_ME_MINIO_SECRET_KEY>>"
    }
---
apiVersion: v1
kind: Secret
metadata:
  namespace: prow-test-pods
  name: s3-credentials
stringData:
  service-account.json: |
    {
      "region": "minio",
      "access_key": "<<CHANGE_ME_MINIO_ACCESS_KEY>>",
      "endpoint": "minio.prow.svc.cluster.local",
      "insecure": true,
      "s3_force_path_style": true,
      "secret_key": "<<CHANGE_ME_MINIO_SECRET_KEY>>"
    }
---