ti-community-lgtm:
  - repos:
      - tidb-community-bots/test-live
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
    review_acts_as_lgtm: true
    pull_owners_endpoint: https://prow.tidb.io/ti-community-owners
  - repos:
      - tikv/community
    review_acts_as_lgtm: true
    pull_owners_endpoint: https://bots.tidb.io/ti-community-bot

ti-community-merge:
  - repos:
      - tidb-community-bots/test-liv
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
    store_tree_hash: true
    pull_owners_endpoint: https://prow.tidb.io/ti-community-owners
  - repos:
      - tikv/community
    store_tree_hash: true
    pull_owners_endpoint: https://bots.tidb.io/ti-community-bot

ti-community-owners:
  - repos:
      - tidb-community-bots/test-live
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
    sig_endpoint: https://bots.tidb.io/ti-community-bot

ti-community-label:
  - repos:
      - tidb-community-bots/test-live
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
    prefixes:
      - status
      - type
