ti-community-lgtm:
  - repos:
      - tidb-community-bots/test-live
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
      - tikv/pd
    review_acts_as_lgtm: true
    pull_owners_endpoint: https://prow.tidb.io/ti-community-owners
  - repos:
      - tikv/community
      - pingcap/community
    review_acts_as_lgtm: true
    pull_owners_endpoint: https://bots.tidb.io/ti-community-bot

ti-community-merge:
  - repos:
      - tidb-community-bots/test-live
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
      - tikv/pd
    store_tree_hash: true
    pull_owners_endpoint: https://prow.tidb.io/ti-community-owners
  - repos:
      - tikv/community
      - pingcap/community
    store_tree_hash: true
    pull_owners_endpoint: https://bots.tidb.io/ti-community-bot

ti-community-owners:
  - repos:
      - tidb-community-bots/test-live
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
    sig_endpoint: https://bots.tidb.io/ti-community-bot
  - repos:
      - tikv/pd
    default_sig_name: scheduling
    trusted_team_for_owners: maintainers
    sig_endpoint: https://bots.tidb.io/ti-community-bot
    require_lgtm_label_prefix: require-LGT

ti-community-label:
  - repos:
      - tidb-community-bots/test-live
      - tidb-community-bots/ti-community-prow
      - tidb-community-bots/ti-community-bot
      - tidb-community-bots/ti-challenge-bot
    prefixes:
      - status
      - type

ti-community-autoresponder:
  - repos:
      - tidb-community-bots/ti-community-prow
    auto_responds:
      - regex: "(?mi)^/ping\\s*$"
        message: "pong"
  - repos:
      - tikv/pd
    auto_responds:
      - regex: "(?mi)^/merge\\s*$"
        message: |
          It seems you want to merge this PR, I will help you trigger all the tests:

          /run-all-tests

