apiVersion: v1
kind: ConfigMap
metadata:
  namespace: prow
  name: plugins
data:
  plugins.yaml: |
    size:
      s: 10
      m: 30
      l: 90
      xl: 270
      xxl: 520
    plugins:
      tidb-community-bots/test-dev:
        - assign
        - branchcleaner
        - help
        - size
        - welcome
        - wip
        - lifecycle
        - help
        - hold
      tidb-community-bots/ti-community-lgtm:
        - assign
        - branchcleaner
        - help
        - size
        - welcome
        - wip
        - lifecycle
        - help
        - hold
      tidb-community-bots/ti-challenge-bot:
        - assign
        - branchcleaner
        - help
        - size
        - welcome
        - wip
        - lifecycle
        - help
        - hold
      tidb-community-bots/ti-community-bot:
        - assign
        - branchcleaner
        - help
        - size
        - welcome
        - wip
        - lifecycle
        - help
        - hold
      tidb-community-bots/ti-community-prow:
        - assign
        - branchcleaner
        - help
        - size
        - welcome
        - wip
        - lifecycle
        - help
        - hold
      tidb-community-bots/ti-community-merge:
        - assign
        - branchcleaner
        - help
        - size
        - welcome
        - wip
        - lifecycle
        - help
        - hold
    external_plugins:
      tidb-community-bots/test-dev:
      - name: ti-community-lgtm
        events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
        - pull_request
      - name: ti-community-merge
        events:
        - issue_comment
        - pull_request_review_comment
        - pull_request