config_updater:
  maps:
    configs/prow/config/config.yaml:
      name: config
    configs/prow/config/plugins.yaml:
      name: plugins
    configs/prow/config/external_plugins_config.yaml:
      name: external-plugins-config
welcome:
  message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> 🎉. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://prow.tidb.io/command-help). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>We want to make sure your contribution gets all the attention it needs! <br><br>Thank you, and welcome to tidb community. :smiley:"
size:
  s: 10
  m: 30
  l: 90
  xl: 270
  xxl: 520
plugins:
  tidb-community-bots/test-dev:
    - assign
    - branchcleaner
    - help
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
  tidb-community-bots/ti-community-lgtm:
    - assign
    - branchcleaner
    - help
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
  tidb-community-bots/ti-challenge-bot:
    - assign
    - branchcleaner
    - help
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
  tidb-community-bots/ti-community-bot:
    - assign
    - branchcleaner
    - help
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
  tidb-community-bots/ti-community-prow:
    - assign
    - branchcleaner
    - help
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
    - config-updater
  tidb-community-bots/ti-community-merge:
    - assign
    - branchcleaner
    - help
    - size
    - welcome
    - wip
    - lifecycle
    - help
    - hold
external_plugins:
  tidb-community-bots/test-dev:
    - name: ti-community-lgtm
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request_review
        - pull_request
    - name: ti-community-merge
      events:
        - issue_comment
        - pull_request_review_comment
        - pull_request