---
apiVersion: v1
kind: Secret
metadata:
  namespace: prow
  name: gcs-credentials
stringData:
  service-account.json: |
    << your_gcs_credentials >>
---
apiVersion: v1
kind: Secret
metadata:
  namespace: prow-test-pods
  name: gcs-credentials
stringData:
  service-account.json: |
    << your_gcs_credentials >>
---